<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
//phpcs:disable Magento2.Files.LineLength.MaxExceeded

$parentBlock = $block->getParentBlock();
$track = $block->getData('track');
$email = $block->getData('storeSupportEmail');
$fields = [
    'Status' => 'getStatus',
    'Signed by' => 'getSignedby',
    'Delivered to' => 'getDeliveryLocation',
    'Shipped or billed on' => 'getShippedDate',
    'Service Type' => 'getService',
    'Weight' => 'getWeight',
];
$number = is_object($track) ? $track->getTracking() : $track['number'];
$trackUrl = '';
?>
<div class="nhsuk-inset-text" style="text-align: left; max-width: 640px; margin-left: auto; margin-right: auto;">
    <span class="nhsuk-u-visually-hidden"><?= $block->escapeHtml(__('Information:')) ?> </span>
    <p><?= $block->escapeHtml(__('If you would like to see more detailed tracking information, please use this number to track your parcel on the relevant delivery providers website.')) ?></p>
</div>
<table class="data table order tracking" id="tracking-table-popup-<?= $block->escapeHtml($number) ?>">
    <caption class="table-caption"><?= $block->escapeHtml(__('Order tracking')) ?></caption>
    <tbody>
    <?php if (is_object($track)) : ?>
        <tr>
            <th class="col label" scope="row"><?= $block->escapeHtml(__('Tracking Number:')) ?></th>
            <td class="col value"><?= $block->escapeHtml($number) ?></td>
        </tr>
        <?php if ($track->getCarrierTitle()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Carrier:')) ?></th>
                <td class="col value"><?= $block->escapeHtml($track->getCarrierTitle()) ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($track->getErrorMessage()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Error:')) ?></th>
                <td class="col error">
                    <?= $block->escapeHtml(__('Tracking information is currently not available. Please ')) ?>
                    <?php if ($parentBlock->getContactUsEnabled()) : ?>
                        <a href="<?= $block->escapeUrl($parentBlock->getContactUs()) ?>" target="_blank"
                           title="<?= $block->escapeHtml(__('contact us')) ?>">
                            <?= $block->escapeHtml(__('contact us')) ?>
                        </a>
                        <?= $block->escapeHtml(__(' for more information or ')) ?>
                    <?php endif; ?>
                    <?= $block->escapeHtml(__('email us at ')) ?>
                    <a href="mailto:<?= /* @noEscape */ $email ?>"><?= /* @noEscape */ $email ?></a>
                </td>
            </tr>
        <?php elseif ($track->getTrackSummary()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Info:')) ?></th>
                <td class="col value"><?= $block->escapeHtml($track->getTrackSummary()) ?></td>
            </tr>
        <?php elseif ($track->getUrl()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Track:')) ?></th>
                <td class="col value">
                    <a href="<?= $block->escapeUrl($track->getUrl()) ?>" target="_blank">
                        <?= $block->escapeUrl($track->getUrl()) ?>
                    </a>
                </td>
            </tr>
        <?php else : ?>
            <?php foreach ($fields as $title => $property) : ?>
                <?php if (!empty($track->$property())) : ?>
                    <tr>
                        <th class="col label" scope="row"><?= /* @noEscape */ $block->escapeHtml(__($title . ':')) ?></th>
                        <td class="col value">
                            <?= $block->escapeHtml($track->$property()) ?>
                        </td>
                    </tr>
                <?php endif;?>
            <?php endforeach; ?>

            <?php if ($track->getDeliverydate()) : ?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml($parentBlock->getDeliveryDateTitle()->getTitle($track)) ?></th>
                    <td class="col value">
                        <?= /* @noEscape */ $parentBlock->formatDeliveryDateTime($track->getDeliverydate(), $track->getDeliverytime()) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endif; ?>
    <?php elseif (isset($track['title']) && isset($track['number']) && $track['number']) : ?>
        <?php /* if the tracking is custom value */ ?>
        <tr>
            <th class="col label" scope="row">
                <?php if (isset($track['title']) && $track['title']) : ?>
                    <?php
                    $trackTitle = preg_replace('/\s+/', '', strtolower($block->escapeHtml($track['title'])));
                    if ($trackTitle == 'dpd') {
                        $trackUrl = 'https://www.dpd.co.uk/apps/tracking/?reference=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'parcelforce') {
                        $trackUrl = 'https://www.parcelforce.com/track-trace?trackNumber='. $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'royalmail') {
                        $trackUrl = 'https://www.royalmail.com/track-your-item?trackNumber='. $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'fedex') {
                        $trackUrl = 'https://www.fedex.com/apps/fedextrack/?tracknumbers=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'dhl') {
                        $trackUrl = 'https://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'ups') {
                        $trackUrl = 'https://www.ups.com/track?loc=en_US&tracknum=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'usps') {
                        $trackUrl = 'https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'tnt') {
                        $trackUrl = 'https://www.tnt.com/express/en_us/site/help/tracking.html?sort=&tracknumber=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'dhlparcel') {
                        $trackUrl = 'https://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=' . $block->escapeHtml($track['number']);
                    } else if ($trackTitle == 'dhlpost') {
                        $trackUrl = 'https://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=' . $block->escapeHtml($track['number']);
                    }
                    ?>
                    <?= $block->escapeHtml($track['title']) ?> (<?= $block->escapeHtml(__('Tracking number')) ?>)
                <?php else : ?>
                    <?= $block->escapeHtml(__('N/A')) ?>
                <?php endif; ?>:
            </th>
            <td class="col value">
                <?php if (isset($track['number']) && $track['number']) : ?>
                    <?= $block->escapeHtml($track['number']) ?><br/><br/>
                    <?php if ($trackUrl !== '') : ?>
                        <div class="nhsuk-action-link" style="font-size: 80%;">
                            <a class="nhsuk-action-link__link" href="<?= $trackUrl ?>"
                               rel="external noopener noreferrer"
                               aria-label="<?= $block->escapeHtml(__('Visit tracking website')) ?> (<?= $block->escapeHtml(__('Opens in a new window')) ?>)"
                               target="_blank">
                                <svg class="nhsuk-icon nhsuk-icon__arrow-right-circle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true" width="36" height="36">
                                    <path d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M12 2a10 10 0 0 0-9.95 9h11.64L9.74 7.05a1 1 0 0 1 1.41-1.41l5.66 5.65a1 1 0 0 1 0 1.42l-5.66 5.65a1 1 0 0 1-1.41 0 1 1 0 0 1 0-1.41L13.69 13H2.05A10 10 0 1 0 12 2z"></path>
                                </svg>
                                <span class="nhsuk-action-link__text"><?= $block->escapeHtml(__('Visit tracking website')) ?></span>
                            </a>
                            <div class="nhsuk-hint">(<?= $block->escapeHtml(__('Opens in a new window')) ?>)</div>
                        </div>

                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>
