<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty std">
    <?php $emptyContent =  $block->getChildHtml('checkout.cart.empty.content'); ?>
    <?php if($emptyContent): ?>
        <?= $emptyContent ?>
    <?php else :?>
        <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
        <p><?= /* @escapeNotVerified */ __('You have no items in your shopping cart.') ?></p>
        <p>
            <div class="nhsuk-action-link">
                <a class="nhsuk-action-link__link" style="text-decoration: none" href="<?=$block->escapeUrl($block->getContinueShoppingUrl())?>">
                    <svg class="nhsuk-icon nhsuk-icon__arrow-right-circle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true" width="36" height="36">
                        <path d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 2a10 10 0 0 0-9.95 9h11.64L9.74 7.05a1 1 0 0 1 1.41-1.41l5.66 5.65a1 1 0 0 1 0 1.42l-5.66 5.65a1 1 0 0 1-1.41 0 1 1 0 0 1 0-1.41L13.69 13H2.05A10 10 0 1 0 12 2z"></path>
                    </svg>
                    <span class="nhsuk-action-link__text"><?= /* @escapeNotVerified */ __('Continue shopping') ?></span>
                </a>
            </div>
        </p>
        <?= $block->getChildHtml('shopping.cart.table.after') ?>
    <?php endif; ?>
</div>
