<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Order by SKU widget template
 *
 * @var $block \Magento\QuickOrder\Block\Sku
 */
?>
<div id="<?= $block->escapeHtmlAttr($block->getUniqueId()) ?>" class="widget block block-addbysku"
     data-role="block-addbysku"
     data-mage-init='{
        "quickOrderItemTable":{
                "addBlockData":{"widgetId":"<?= $block->escapeHtmlAttr($block->getUniqueId()) ?>"},
                "addEvent":"addNewRow",
                "addSelector":"[data-role=new-block]"
        }
     }'>
    <div data-role="show-errors" class="wrap-sum-errors" data-mage-init='{
        "countingErrors":{
                "wrapError":"[data-role=block-addbysku]",
                "nameErrorBlock":"[data-role=error-message]"
        }
     }'></div>
    <?php if (!$block->getIsTitleHidden()): ?>
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= $block->escapeHtml(__('Order by SKU')) ?></strong>
        </div>
    <?php endif ?>
    <div class="block-content">
        <form
                class="form form-addbysku"
                action="<?= $block->escapeUrl($block->getUrl('quickorder/sku/uploadfile')) ?>"
                method="post"
                data-role="send-sku"
                data-mage-init='{"validation":{}, "quickOrderAddToCart":{}}'
            <?php if ($block->getIsMultipart()): ?> enctype="multipart/form-data"<?php endif; ?>
        >
            <div class="form-addbysku-inner">
                <div class="box box-items">
                    <fieldset class="fieldset" data-container="items">
                        <legend class="nhsuk-u-visually-hidden"><?= $block->escapeHtml(__('Enter SKU or Product name and quantity')) ?></legend>
                        <div class="fields additional deletable-item-title">
                            <div class="field sku required">
                                <label class="label">
                                    <span><?= $block->escapeHtml(__('Enter SKU or Product Name')) ?></span>
                                </label>
                            </div>
                            <div class="field qty required">
                                <label class="label">
                                    <span><?= $block->escapeHtml(__('Qty')) ?></span>
                                </label>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <?php if ($block->getChildHtml()): ?>
                    <div class="box box-upload">
                        <fieldset class="fieldset">
                            <legend class="nhsuk-u-visually-hidden"><?= $block->escapeHtml(__('Enter upload csv')) ?></legend>
                            <?= $block->getChildHtml() ?>
                        </fieldset>
                    </div>
                <?php endif; ?>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                            class="action tocart primary"
                            data-action="submit-sku"
                            disabled>
                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                    </button>
                </div>
            </div>
            <?php if ($block->getLink()): ?>
                <?= /* @noEscape */ $block->getLink() ?>
            <?php endif; ?>
        </form>
        <script data-template="add-block" type="text/x-magento-template">
            <div class="fields additional deletable-item" data-role="new-block"
                 data-mage-init='{
                     "deletableItem":{},
                     "productSkuItem":{
                        "rowIndex": "<%- data.rowIndex %>",
                        "tableWigetSelector":"[data-role=block-addbysku]",
                        "urlSku":"<?= $block->escapeUrl($block->getUrl('quickorder/ajax/search')) ?>",
                        "urlDelete":"<?= $block->escapeUrl($block->getUrl('quickorder/ajax/delete')) ?>"}}'>
                <div class="field sku required ui-front">
                    <label class="label" for="id-items<%- data.widgetId %><%- data.rowIndex %>sku">
                        <span><?= $block->escapeHtml(__('Enter SKU or Product Name')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="items[<%- data.rowIndex %>][sku]"
                               id="id-items<%- data.widgetId %><%- data.rowIndex %>sku"
                               data-id="<%- data.widgetId %><%- data.rowIndex %>sku"
                               data-sku="true"
                               aria-required="true"
                               data-mage-init='{
                                    "Magento_QuickOrder/js/sku/autocomplete": {
                                        "sourceUrl":
                                        "<?= $block->escapeUrl($block->getUrl('quickorder/ajax_product/suggest')) ?>"
                                    }
                               }'
                               data-validate='{
                                    "required-if-all-sku-empty-and-file-not-loaded": {
                                        specifiedId: "#customer_sku_csv",
                                        dataSku: "data-sku"
                                        }
                               }'
                               data-role="product-sku"/>
                        <div class="product-block" data-role="product-block"></div>

                    </div>
                </div>
                <div class="field qty required">
                    <label class="label" for="id-items<%- data.widgetId %><%- data.rowIndex %>qty">
                        <span><?= $block->escapeHtml(__('Qty')) ?></span>
                    </label>
                    <div class="control">
                        <input type="number"
                               name="items[<%- data.rowIndex %>][qty]"
                               id="id-items<%- data.widgetId %><%- data.rowIndex %>qty"
                               class="qty"
                               maxlength="13"
                               aria-required="true"
                               data-validate='{
                                    "required-number-if-specified":
                                    "[data-id=<%- data.widgetId %><%- data.rowIndex %>sku]",
                                    "validate-number": true,
                                    "validate-greater-than-zero": true,
                                    "validate-number-range": "0.0001-99999999.9999"
                                    }'
                               data-role="product-qty"/>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="secondary">
                        <button type="button" class="action remove"
                                title="<?= $block->escapeHtmlAttr(__('Remove Row')) ?>" data-role="delete">
                            <span><?= $block->escapeHtml(__('Remove Row')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </script>
    </div>
</div>
