<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table role="table" class="data table table-order-items history nhsuk-table-responsive" id="my-orders-table">
            <caption class="table-caption nhsuk-table__caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead role="rowgroup" class="nhsuk-table__head">
            <tr role="row">
                <th role="columnheader" scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th role="columnheader" scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th role="columnheader" scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th role="columnheader" scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th role="columnheader" scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody class="nhsuk-table__body">
            <?php foreach ($_orders as $_order) : ?>
                <tr role="row" class="nhsuk-table__row">
                    <td role="cell" data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id nhsuk-table__cell"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td role="cell" data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date nhsuk-table__cell"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td role="cell" data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total nhsuk-table__cell"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td role="cell" data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status nhsuk-table__cell"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td role="cell" data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions nhsuk-table__cell">
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            <span class="nhsuk-u-visually-hidden"> <?= $block->escapeHtml($_order->getRealOrderId()) ?></span>
                        </a>
                        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?= /* @noEscape */
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                <span class="nhsuk-u-visually-hidden"> <?= $block->escapeHtml($_order->getRealOrderId()) ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
