<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Order by SKU Failed Items renderer
 */
// phpcs:disable Magento2.Templates.ThisInTemplate
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer
 * @var $escaper \Magento\Framework\Escaper
 */

/** @var \Magento\Quote\Model\Quote\Item\AbstractItem $_item */
$_item = $block->getItem();

/** @var \Magento\Tax\Helper\Data $helper */
$helper = $this->helper(\Magento\Tax\Helper\Data::class);
$additionalInfoBlock = $block->getProductAdditionalInformationBlock();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$maxQuantity = -1;
if ($_item->getQtyMaxAllowed()) {
    $maxQuantity = $_item->getQtyMaxAllowed();
}

$canApplyMsrp = false;
if ($block->moduleManager->isEnabled('Magento_Msrp')) {
    /**
     * @var \Magento\Msrp\Helper\Data $msrpHelper
     */
    $msrpHelper = $this->helper(\Magento\Msrp\Helper\Data::class);
    $canApplyMsrp = $msrpHelper->
        isShowBeforeOrderConfirm($_item->getProduct()) && $msrpHelper->isMinimalPriceLessMsrp($_item->getProduct());
}

// disable the qty field if there is no product associated with the sku (i.e. invalid sku) or if sku failed for
// out of stock scenario
$qtyDisabled = !$block->hasProductUrl() ||
        $_item->getCode() == \Magento\AdvancedCheckout\Helper\Data::ADD_ITEM_STATUS_FAILED_OUT_OF_STOCK;
?>
<tbody class="nhsuk-table__body cart item" data-mage-init='{"orderBySkuFailure":{}}'>
    <tr role="row" class="nhsuk-table__row item-info">
        <td data-th="<?= $escaper->escapeHtmlAttr(__('Item')) ?>" role="cell" class="nhsuk-table__cell col item">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
                   class="product-item-photo"
                   tabindex="-1">
            <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($_item->getProduct(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <?php if ($block->getProductName()): ?>
                    <strong class="product-item-name">
                        <?php if ($block->hasProductUrl()): ?>
                            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>">
                                <?= $escaper->escapeHtml($block->getProductName()) ?>
                            </a>
                        <?php else: ?>
                            <?= $escaper->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                <?php endif; ?>
                <?php if ($additionalInfoBlock): ?>
                    <?= $additionalInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
            </div>
        </td>
        <td data-th="<?= $escaper->escapeHtmlAttr(__('Price')) ?>" role="cell" class="nhsuk-table__cell col price">
            <?php if ($canApplyMsrp): ?>
                <span class="msrp notice"><?= $escaper->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getProduct()->getId(); ?>
                    <a
                        href="#"
                        class="action help map"
                        id="<?= $escaper->escapeHtmlAttr($helpLinkId) ?>"
                        data-mage-init='{
                            "addToCart":{
                                "helpLinkId": "#<?= $escaper->escapeHtmlAttr($helpLinkId) ?>",
                                "productName": "<?= $escaper->escapeHtmlAttr($_item->getProduct()->getName()) ?>",
                                "showAddToCart": false
                            }
                        }'>
                        <span><?= $escaper->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            <?php else: ?>
                <?php if ($helper->displayPriceIncludingTax() || $helper->displayBothPrices()): ?>
                    <?php $priceIncludingTax = $this->helper(\Magento\Catalog\Helper\Data::class)->getTaxPrice(
                        $_item->getProduct(),
                        $_item->getBaseCalculationPrice(),
                        true
                    ); ?>
                    <span
                        class="price-including-tax"
                        data-label="<?= $escaper->escapeHtmlAttr(__('Incl. Tax')) ?>">
                        <span
                            class="cart-price"><?= /* @noEscape */ $block->convertPrice($priceIncludingTax, true) ?>
                        </span>
                    </span>
                <?php endif; ?>
                <?php if ($helper->displayPriceExcludingTax() || $helper->displayBothPrices()): ?>
                    <?php $priceExcludingTax = $this->helper(\Magento\Catalog\Helper\Data::class)->getTaxPrice(
                        $_item->getProduct(),
                        $_item->getBaseCalculationPrice(),
                        false
                    ); ?>
                    <span
                        class="price-excluding-tax"
                        data-label="<?= $escaper->escapeHtmlAttr(__('Excl. Tax')) ?>">
                        <span
                            class="cart-price"><?= /* @noEscape */ $block->convertPrice($priceExcludingTax, true) ?>
                        </span>
                    </span>
                <?php endif; ?>
            <?php endif ?>
        </td>
        <td data-th="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>" role="cell" class="nhsuk-table__cell col qty">
            <?php $validateItemQuantityCheck = false; ?>
            <div class="control qty">
                <input name="cart[<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>][qty]"
                    value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                    size="4"
                    type="number"
                    class="input-text qty <?= ($qtyDisabled) ? 'disabled' : '' ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                    data-role="input-qty"
                    <?php if ($qtyDisabled): ?>
                        disabled="disabled"
                    <?php endif; ?>
                    data-validate="{'required': true,'validate-greater-than-zero': true, 'validate-item-quantity': {
                        <?php if ($_item->getQtyMinAllowed()): ?>
                            'minAllowed': <?= $escaper->escapeHtmlAttr($_item->getQtyMinAllowed());
                                $validateItemQuantityCheck = true ?>
                        <?php endif ?>
                        <?php if ($maxQuantity > 0): ?>
                            <?php if ($validateItemQuantityCheck): ?>
                                ,
                            <?php endif ?>
                            'maxAllowed': <?= $escaper->escapeHtmlAttr($maxQuantity);
                                $validateItemQuantityCheck = true ?>
                        <?php endif; ?>
                        <?php if ($_item->getQtyIncrements() > 0): ?>
                            <?php if ($validateItemQuantityCheck): ?>
                                ,
                            <?php endif ?>
                            'qtyIncrements': <?= $escaper->escapeHtmlAttr($_item->getQtyIncrements()) ?>
                        <?php endif; ?>
                        }}"
                    data-role="cart-item-qty"/>
            </div>
        </td>
    </tr>
    <tr role="row" class="nhsuk-table__row item-actions">
        <td role="cell" class="nhsuk-table__cell" colspan="3">
            <div class="actions-toolbar">
                <button title="<?= $escaper->escapeHtmlAttr(__('Remove item')) ?>"
                        type="button"
                        class="action action-delete"
                        data-post='<?= /* @noEscape */
                        $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode(
                            ['action' => $block->getDeleteUrl(), 'data' => []]
                        ) ?>'
                >
                    <span>
                        <?= $escaper->escapeHtml(__('Remove item')) ?>
                    </span>
                </button>
            </div>
        </td>
    </tr>
</tbody>
