<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><h2><?= $block->escapeHtml(__('Account Information')) ?></h2></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <dl class="nhsuk-summary-list">
                    <div class="nhsuk-summary-list__row">
                        <dt class="nhsuk-summary-list__key">
                            <?= __('Name') ?>
                        </dt>
                        <dd class="nhsuk-summary-list__value">
                            <?= $block->escapeHtml($block->getName()) ?>
                        </dd>

                        <dd class="nhsuk-summary-list__actions">

                            <a href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                                Change<span class="nhsuk-u-visually-hidden"> <?= __('Name') ?></span>
                            </a>

                        </dd>

                    </div>

                    <div class="nhsuk-summary-list__row">
                        <dt class="nhsuk-summary-list__key">
                            <?= __('Email') ?>
                        </dt>
                        <dd class="nhsuk-summary-list__value">
                            <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
                        </dd>

                        <dd class="nhsuk-summary-list__actions">

                            <a href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                                Change<span class="nhsuk-u-visually-hidden"> <?= __('Email') ?></span>
                            </a>

                        </dd>

                    </div>
                    <div class="nhsuk-summary-list__row">
                        <dt class="nhsuk-summary-list__key">
                            <?= __('Phone Number') ?>
                        </dt>
                        <dd class="nhsuk-summary-list__value">
                            <?php if(($block->getCustomer()->getCustomAttribute("customer_telephone"))): ?>
                                <?= $block->escapeHtml($block->getCustomer()->getCustomAttribute("customer_telephone")->getValue()) ?>
                                <?php if($block->getCustomer()->getCustomAttribute("customer_telephone")->getValue() == "1234"): ?>
                                    </br>
                                    <strong class="nhsuk-tag nhsuk-tag--red">
                                        <?= __('Requires Update') ?>
                                    </strong>
                                <?php endif; ?>
                                <?php else:?>
                                <strong class="nhsuk-tag nhsuk-tag--red">
                                    <?= __('Requires Update') ?>
                                </strong>
                            <?php endif;?>
                        </dd>

                        <dd class="nhsuk-summary-list__actions">
                            <a href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                                Change<span class="nhsuk-u-visually-hidden"> <?= __('Phone Number') ?></span>
                            </a>
                        </dd>
                    </div>
                </dl>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <!--<div class="box-actions">
                <a class="action edit" href="<?/*= $block->escapeUrl($block->getUrl('customer/account/edit')) */?>">
                    <span><?/*= $block->escapeHtml(__('Edit')) */?></span>
                </a>
                <a href="<?/*= $block->escapeUrl($block->getChangePasswordUrl()) */?>" class="action change-password">
                    <?/*= $block->escapeHtml(__('Change Password')) */?>
                </a>
            </div>-->
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>">
                        <span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml('additional_blocks'); ?>
    </div>
</div>
