<!-- Add Readmore link using JS to attribute overview text -->
<script type="text/x-magento-init">
    {
        ".product.attribute.overview .value": {
            "productAttributeOverview": {
                "label": "<?= /* @escapeNotVerified */ __('Read more') ?>",
                "href": "#tab-label-description-title",
                "clickTarget": "#tab-label-description-title"
            }
        }
    }
</script>