<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="fields additional">
    <div class="field sku">
        <label for="multiple_skus" class="label">
            <span><?= $block->escapeHtml(__('Enter Multiple SKUs')) ?></span>
        </label>
        <div class="note">
            <p><?= $block->escapeHtml(__('Use commas or paragraph to separate SKUs.')) ?></p>
        </div>
        <div class="control">
            <textarea
                name="multiple_skus"
                data-role="multiple-skus"
                id="multiple_skus"
                data-id="multiple_skus"
                aria-required="false"
                rows="3"
                class="input-text"
                ></textarea>
        </div>
    </div>
</div>
<div class="actions-toolbar">
    <div class="secondary">
        <button type="button"
                title="<?= $block->escapeHtmlAttr(__('Add to List')) ?>"
                class="action move-to-single-skus"
                data-mage-init='{"quickOrderMultipleSkus":{
                "urlSku":"<?= /* @noEscape */ $block->getUrl('quickorder/ajax/search') ?>"
                }}'>
            <span><?= $block->escapeHtml(__('Add to List')) ?></span>
        </button>
    </div>
</div>
