<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
/** @var \Magento\Cookie\Helper\Cookie $cookieHelper */
$cookieHelper = $block->getData('cookieHelper');
if ($cookieHelper->isCookieRestrictionModeEnabled()): ?>
    <div role="alertdialog"
         tabindex="-1"
         id="notice-cookie-block">
        <div id="nhsuk-cookie-banner">
            <div class="nhsuk-cookie-banner" id="cookiebanner" role="document" tabindex="0">
                <div class="nhsuk-width-container">
                    <h2><?= $block->escapeHtml(__("Cookies on the NHS Supply Chain")) ?></h2>
                    <p><?= $block->escapeHtml(__("We've put some small files called cookies on your device to make our site work.")) ?></p>
                    <p><?= $block->escapeHtml(__("We'd also like to use analytics cookies. These send anonymous information about how our site is used to a service called Google Analytics. We use this information to improve our site.")) ?></p>
                    <p><?= $block->escapeHtml(__("Let us know if this is OK. We'll use a cookie to save your choice. You can <a id=\"nhsuk-cookie-banner__link\" href=\"%1\" tabindex=\"1\">read more about our cookies</a> before you choose.", $block->getPrivacyPolicyLink()), ['a']) ?></p>
                    <ul>
                        <li><button class="nhsuk-button" id="nhsuk-cookie-banner__link_accept_analytics" tabindex="2"><?= $block->escapeHtml(__("I'm OK with analytics cookies")) ?></button></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#notice-cookie-block') ?>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#nhsuk-cookie-banner__link_accept_analytics",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->getUrl('cookie/index/noCookies')) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
