<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Order by SKU Failed Items grid
 *
 * @var $block \Magento\AdvancedCheckout\Block\Sku\Products
 */
// phpcs:disable Magento2.Files.LineLength
// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<div class="block block-cart-failed">
    <div class="block-title"><h2><?= $block->escapeHtml(__('Products Requiring Attention')) ?></h2></div>
    <div class="block-content">
        <form action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="post" data-mage-init='{"validation": {}}' class="form form-cart-failed">
            <div class="cart table-wrapper">
                <table role="table"  d="failed-products-table" class="nhsuk-table-responsive cart items data failed">
                    <caption class="nhsuk-table__caption nhsuk-u-visually-hidden" style="width: auto"><?= $block->escapeHtml(__('Products Requiring Attention')) ?></caption>
                    <?php $mergedCells = ($this->helper(\Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
                    <thead role="rowgroup">
                    <tr role="row">
                        <th role="columnheader" class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                        <th role="columnheader" class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                        <th role="columnheader" class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
                    </tr>
                    </thead>
                    <?php foreach ($block->getItems() as $_item) : ?>
                        <?= $block->getItemHtml($_item) ?>
                    <?php endforeach ?>
                </table>
            </div>
            <div class="cart primary actions">
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                        class="action tocart">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </div>
        </form>
        <form action="<?= $block->escapeUrl($block->getDeleteAllItemsUrl()) ?>" method="post" data-mage-init='{"validation": {}}' class="form form-cart-failed">
            <div class="cart secondary actions">
                <button id="remove_all_failed_items"
                        type="submit"
                        class="action clear"
                        title="<?= $block->escapeHtml(__('Remove All')) ?>">
                    <span><?= $block->escapeHtml(__('Remove All')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
