<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php /** @var  $block \Magento\Shipping\Block\Items */ ?>
<?php  $_order = $block->getOrder() ?>
    <div class="actions-toolbar">
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <?= $block->getChildHtml('track-all-link') ?>
        <?php endif; ?>
        <a href="<?= $block->escapeUrl($block->getPrintAllShipmentsUrl($_order)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $block->escapeHtml(__('Print All Shipments')) ?></span>
        </a>
    </div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment) : ?>
    <div class="order-title">
        <strong><?= $block->escapeHtml(__('Shipment #')) ?><?= $block->escapeHtml($_shipment->getIncrementId()) ?></strong>
        <a href="<?= $block->escapeUrl($block->getPrintShipmentUrl($_shipment)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $block->escapeHtml(__('Print Shipment')) ?></span>
        </a>
        <a href="#"
           data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($_shipment)) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
           title="<?= $block->escapeHtml(__('Track this shipment')) ?>"
           class="action track">
            <span><?= $block->escapeHtml(__('Track this shipment')) ?></span>
        </a>
    </div>
    <br/>
    <?php $tracks = $_shipment->getTracksCollection(); ?>
    <?php  if ($tracks->count()) : ?>
        <div id="my-tracking-table-<?= (int) $_shipment->getId() ?>" class="nhsuk-inset-text">
            <span class="nhsuk-u-visually-hidden">Information: </span>
            <p><strong><?= $block->escapeHtml(__('Tracking Number(s):')) ?></strong>   <?php
                $i = 1;
                $_size = $tracks->count();
                foreach ($tracks as $track) : ?>
                    <?php if ($track->isCustom()) : ?>
                        <?= $block->escapeHtml($track->getNumber()) ?>
                    <?php else : ?>
                        <a href="#"
                           data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($track)) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'
                           class="action track"><span><?= $block->escapeHtml($track->getNumber()) ?></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($i != $_size) : ?>, <?php endif; ?>
                    <?php $i++;
                endforeach; ?></p>
        </div>
    <?php  endif; ?>
    <div class="table-wrapper order-items-shipment">
        <table class="data table table-order-items shipment nhsuk-table-responsive" id="my-shipment-table-<?= (int) $_shipment->getId() ?>">
            <caption class="table-caption nhsuk-table__caption"><?= $block->escapeHtml(__('Items Shipped')) ?></caption>
            <thead role="rowgroup" class="nhsuk-table__head">
            <tr role="row">
                <th role="columnheader" scope="col" class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th role="columnheader" scope="col" class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                <th role="columnheader" scope="col" class="col qty"><?= $block->escapeHtml(__('Qty Shipped')) ?></th>
            </tr>
            </thead>
            <?php $_items = $_shipment->getAllItems(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody class="nhsuk-table__body">
                    <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
    <?= $block->getCommentsHtml($_shipment) ?>
<?php endforeach; ?>