<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Items\Grid
 */

$itemsList =  $block->getRequisitionListItems();

?>
<div class="requisition-content" data-mage-init='{"requisitionActions":{ }}'>
    <?= $block->getChildHtml('requisition.management') ?>
    <?php if (empty($itemsList)) : ?>
        <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in this requisition list.'))  ?></span></div>
    <?php else : ?>
        <div class="requisition-grid table-wrapper">
            <form
                action="<?= $block->escapeUrl($block->getUrl('*/item/update', [
                    'requisition_id' => (int)$block->getRequest()->getParam('requisition_id')
                ])) ?>"
                method="post"
                data-mage-init='{"validation":{}}'
                id="form-requisition-list"
                >
                <table role="table" class="nhsuk-table-responsive">
                    <caption class="nhsuk-table__caption nhsuk-u-visually-hidden"><?= $block->escapeHtml(__('Requisition list'))  ?></caption>
                    <thead role="rowgroup" class="nhsuk-table__head">
                    <tr role="row">
                        <th role="columnheader" scope="col" class="col number"><span>#</span></th>
                        <th role="columnheader" scope="col" class="col product" colspan="2">
                            <span data-print-label="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
                                <?= $block->escapeHtml(__('Item')) ?>
                            </span>
                        </th>
                        <th role="columnheader" scope="col" class="col price">
                            <span><?= $block->escapeHtml(__('Price')) ?></span>
                        </th>
                        <th role="columnheader" scope="col" class="col qty">
                            <span><?= $block->escapeHtml(__('Qty')) ?></span>
                        </th>
                        <th role="columnheader" scope="col" class="col subtotal action">
                            <span><?= $block->escapeHtml(__('Subtotal')) ?></span>
                        </th>
                    </tr>
                    </thead>
                    <tbody class="nhsuk-table__body">
                    <?php $i = 0 ?>
                    <?php foreach ($itemsList as $item) : $i++ ?>
                        <tr role="row" class="nhsuk-table__row" class="_<?= ($i % 2) ? 'even' : 'odd' ?> item"
                            data-product-id="<?= (int) $item->getId() ?>">
                            <td role="cell" class="nhsuk-table__cell" class="col number">
                                <span class="nhsuk-table-responsive__heading"><?= $block->escapeHtmlAttr(__('No.')) ?> </span>
                                <?= (int) $i ?>
                            </td>
                            <?php
                                $block->getChildBlock('requisition.list.item.view')
                                    ->setItem($item)
                                    ->setItemErrors($block->getItemErrors($item));
                            ?>
                            <?= $block->getChildHtml('requisition.list.item.view', false) ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

                <?= $block->getChildHtml('requisition.items.buttons') ?>
            </form>
        </div>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition.item.grid.selection.provider": {
                        "component": "Magento_RequisitionList/js/requisition/items/grid/selection-provider",
                        "selectionSelector": "[data-action='requisition-item-check']"
                    }
                }
            }
        }
    }
</script>
