<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Item
 */
$item = $block->getItem();
?>
<td role="cell" class="nhsuk-table__cell col col-checkbox">
    <span class="nhsuk-table-responsive__heading"><?= $block->escapeHtmlAttr(__('Select')) ?> </span>
    <div class="field choice">
        <input name="<?= $block->escapeHtmlAttr($item->getSku()) ?>"
               class="input-checkbox checkbox"
               type="checkbox"
               id="<?= (int) $item->getId() ?>"
               data-item-id="<?= (int) $item->getId() ?>"
               data-item-has-errors="<?= (int)!empty($item->getItemErrors()) ?>"
               data-action="requisition-item-check"
               data-role="select-item"
               value="1"/>
        <label class="label" for="<?= (int) $item->getId() ?>">
            <span class="nhsuk-u-visually-hidden">
                <?= $block->escapeHtmlAttr(__('Select item')) ?> <?= (int) $item->getId() ?>
            </span>
        </label>
    </div>
</td>
<td role="cell" class="nhsuk-table__cell col product" data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>">
    <span class="nhsuk-table-responsive__heading"><?= $block->escapeHtmlAttr(__('Product')) ?> </span>
    <div class="product-item-description">
        <?php if ($block->getRequisitionListProduct()) : ?>
            <span class="product-item-name">
                <a href="<?= $block->escapeUrl($block->getProductUrlByItem()) ?>">
                    <?= $block->escapeHtml($block->getRequisitionListProduct()->getName()) ?>
                </a>
            </span>
        <?php endif ?>
        <div class="product-item-sku">
            <b><?= $block->escapeHtml(__('SKU')) ?>:</b>
            <span><?= $block->escapeHtml($item->getSku()) ?></span>
        </div>
        <?php $block->getChildBlock('requisition.list.item.options')->setItem($item); ?>
        <?= $block->getChildHtml('requisition.list.item.options', false) ?>
        <?php if ($block->getItemError()) : ?>
            <div class="message error item-error">
                <span><?= $block->escapeHtml($block->getItemError()) ?></span>
            </div>
        <?php endif ?>
    </div>
    <div class="product-item-image">
        <img src="<?= $block->escapeUrl($block->getImageUrl()) ?>" alt="<?= $block->getRequisitionListProduct() ? $block->escapeUrl($block->getRequisitionListProduct()->getName()) : '' ?>">
    </div>
</td>
<td role="cell" class="nhsuk-table__cell col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>" style="text-align: right">
    <span class="nhsuk-table-responsive__heading"><?= $block->escapeHtmlAttr(__('Price')) ?> </span>
    <?php if (!$block->isOptionsUpdated() && $block->getRequisitionListProduct()) : ?>
        <?= /* @noEscape */ $block->getFormattedPrice() ?>
        <?php if ($block->displayBothPrices()) : ?>
            <span class="price-excluding-tax"
                  data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
                <?= /* @noEscape */ $block->getFormattedPriceExcludingTax() ?>
            </span>
        <?php endif; ?>
    <?php endif ?>
</td>
<td role="cell" class="nhsuk-table__cell col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>" style="text-align: right">
    <span class="nhsuk-table-responsive__heading"><?= $block->escapeHtmlAttr(__('Qty')) ?> </span>
    <input id="item-<?= (int) $item->getId() ?>-qty"
           name="qty[<?= (int) $item->getId() ?>]"
           value="<?= (float) ($item->getQty() * 1) ?>"
        <?php if (!$block->canEditQty()) : ?>
            disabled="disabled"
        <?php endif; ?>
           type="number"
           size="4"
           class="input-text qty"
           data-validate='{
                "validate-number": true,
                "validate-greater-than-zero": true,
                "required": true
                }'
           data-role="requisition-item-qty"/>
    <label class="nhsuk-u-visually-hidden" for="item-<?= (int) $item->getId() ?>-qty" ><?= $block->escapeHtmlAttr(__('Qty')) ?></label>
</td>
<td role="cell" class="nhsuk-table__cell col subtotal action" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>" style="text-align: right">
    <span class="nhsuk-table-responsive__heading"><?= $block->escapeHtmlAttr(__('Subtotal')) ?> </span>
    <div class="product-item-subtotal">
        <?php if (!$block->isOptionsUpdated() && $block->getRequisitionListProduct()) : ?>
            <?= /* @noEscape */ $block->getFormattedSubtotal() ?>
            <?php if ($block->displayBothPrices()) : ?>
                <span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
                    <?= /* @noEscape */ $block->getFormattedSubtotalExcludingTax() ?>
                </span>
            <?php endif; ?>
        <?php endif ?>
        <div class="actions-toolbar">
            <?php if ($block->canEdit()) : ?>
                <button type="button"
                        title="<?= $block->escapeHtmlAttr(__('Edit item')) ?>"
                        data-action="edit-item"
                        data-update-item='{
                            "editItemUrl":"<?= $block->escapeUrl($block->getItemConfigureUrl()) ?>"
                        }'
                        class="action action-edit">
                    <span><?= $block->escapeHtml(__('Edit item')) ?></span>
                </button>
            <?php endif; ?>
            <button type="button"
                    title="<?= $block->escapeHtmlAttr(__('Remove item')) ?>"
                    data-action="remove-item"
                    data-delete-list='{
                        "deleteUrl":"<?= $block->escapeUrl(
                        $block->getUrl('*/item/delete', ['requisition_id' => (int)$block->getRequest()->getParam('requisition_id')])
                    ) ?>",
                        "itemId": "<?= (int) $item->getId() ?>"
                    }'
                    class="action action-delete">
                <span><?= $block->escapeHtml(__('Remove item')) ?></span>
            </button>
        </div>
    </div>
</td>
